### ISSUE TITLE
Issues list unreadable with description

### ISSUE THREAD

**Issue by xlat** [rozpuszczalny/vscode-redmine#2]
Hi, 
First I want to say thats a good works !

We have issues with long description, multi lines, some time containing images, and I found it was not really readable from the QuickPick list as you can see on the following screen shot:

![](https://framapic.org/7DLYdnLK2AZH/yKLVUcRcdncU)

I don't know if it is possible to adjust the way it is rendered, so I just commented the description in extension.ts@68 to make it more readable for me ;-)

**Comment by rozpuszczalny** [comment]
Hi,
Thanks for using my extension, I really appreciate it!

This issue came out with a new version of VSCode. I've just run this extension, and issues, which were displayed properly, now are messy like yours. I've solved it by removing new line characters. However, I think I'll remove issue description in QuickPick list as soon as I'll manage to make some kind of issue editor, like mentioned in #1.
