### ISSUE TITLE
Quick update, doesn't offer groups as assignee

### ISSUE THREAD

**Issue by dlabi** [rozpuszczalny/vscode-redmine#53]
**Describe the bug**

Quick update in step 2 hasn't groups in drop down. So if your current assignee is group you have to select just individual developer. 

**To Reproduce**

1. Select any ticket
2. Select "Quick update"
3. Proceed to selection of assignee
4. See that groups isn't in the list

**Expected behavior**

Groups needs to be selectable from drop down menu too

**Screenshots**

**Additional context**

**Comment by rozpuszczalny** [comment]
Hey, thanks for the report! To be honest, I didn't know it was possible to assign a group to the ticket. But yeah, I've activated the setting via "Administration > Issue tracking > Allow issue assignment to groups" and it is possible.

Anyway, whoever will fix it (me or somebody else), needs to investigate when to actually display groups in the assignee selection, because it will not be valid to present groups when the Redmine would have this option set to false.

**Comment by dlabi** [comment]
yes we are using groups if there is ticket which can be solved by any first free developer.
